CREATE DATABASE WATERFERN;

CREATE TABLE USER(
    ID SERIAL PRIMARY KEY,
    PASSWORD VARCHAR(50) NOT NULL
);

CREATE TABLE CLASSES(
    ID SERIAL PRIMARY KEY,
    COURSE.CODE VARCHAR(8) NOT NULL
);

CREATE TABLE OFFERINGS(
    ID SERIAL PRIMARY KEY,
    CLASS_ID INT,
    SEMESTER DATE,
    DONE INT,
    FOREIGN KEY(CLASS_ID) REFERENCES CLASS(ID)
);

CREATE TABLE ASSIGNMENTS(
    ID SERIAL PRIMARY KEY,
    OFFERING_ID INT,
    OPENING DATE,
    CLOSE DATE,
    FOREIGN KEY(OFFERING_ID) REFERENCES OFFERINGS(ID)
);

CREATE TABLE SUBMISSIONS(
    ID SERIAL PRIMARY KEY,
    ASSIGN_ID INT,
    USER_ID INT,
    LATE INT,
    DATA BYTEA,
    LANGUAGE VARCHAR,
    FOREIGN KEY(ASSIGN_ID) REFERENCES ASSIGNMENTS,
    FOREIGN KEY(USER_ID) REFERENCES USER
);

CREATE TABLE INDEX(
    BLOCK_ID SERIAL NOT NULL UNIQUE,
    SUBMISSION_ID INT NOT NULL,
    START_LINE INT NOT NULL,
    END_LINE INT NOT NULL,
    INDEX REAL[] NOT NULL,
    TYPE VARCHAR NOT NULL
    PRIMARY KEY (SUBMISSION_ID, START_LINE, END_LINE, TYPE),
    FOREIGN KEY (SUBMISSION_ID) REFERENCES SUBMISSIONS(ID)
);

CREATE TABLE ASSOCIATIONS(
    DOCUMENT1 INT NOT NULL, 
    DOCUMENT2 INT NOT NULL, 
    INDEX1 INT NOT NULL, 
    INDEX2 INT NOT NULL, 
    SIMILARITY REAL NOT NULL,
    FOREIGN KEY (DOCUMENT1) REFERENCES SUBMISSIONS(ID),
    FOREIGN KEY (DOCUMENT2) REFERENCES SUBMISSIONS(ID),
    FOREIGN KEY (INDEX1) REFERENCES INDEX(BLOCK_ID),
    FOREIGN KEY (INDEX2) REFERENCES INDEX(BLOCK_ID)
);